
/// Get objects in cars.json file
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

// Enter information about the new object before sending request. 

{
    "brand": "Räserbil",
    "modelname": "Supersnabb",
    "color": "Black"
}

###
// Enter ID of the item on line 20 & 24. Then enter the new (updated) information before sending request. 
PUT http://localhost:3000/abc123
Content-Type: application/json

{
    "id": "abc123",
    "brand": "apsdjasdklj",
    "modelname": "asdasdasd",
    "color": "XXasdasdasdasXX"
}

###
// Change the id (abc123) in the address to the ID of the object you want to delete. 
DELETE http://localhost:3000/abc123
