
/// Hämta information
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

// Fyll i önskad information innan du skickar request
{
    "id": 2,
    "brand": "asdasdasdasd",
    "modelname": "V90",
    "color": "Red"

}

###

PUT http://localhost:3000/

###

DELETE http://localhost:3000/