
/// Get objects in cars.json file
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

// Enter information about the new object before sending request. 

{
    "brand": "Räserbil",
    "modelname": "Supersnabb",
    "color": "Black"
}

###

//Change the id (abc123) to the id of the item you want to update 
//before sending the request.
PUT http://localhost:3000/abc123
Content-Type: application/json

{
    "id": "abc123",
    "brand": "apsdjasdklj",
    "modelname": "asdasdasd",
    "color": "XXasdasdasdasXX"
}

###
// Change the id (abc123) to the ID of the object you want to delete. 
DELETE http://localhost:3000/abc123
